### ISSUE TITLE
Enable svutRun to autorun tests on file save

### ISSUE THREAD

**Issue by sarahec** [damofthemoon/svut#8]
Proposal:
1. Add a `--watch` option to svutRun. It should run the appropriate test(s) when a test or source file changes.
2. Respect the --tests flag (or absence thereof) to determine which tests to run.

Proposed enhancements:
3. Detect when a compilation error will prevent a test from running and raise a warning.
4. Capture the output of all tests and print a summary at the end. (Minimizes scrolling.) This would live behind a feature flag.

(Please assign to me. I will file subsidiary bugs for the enhancements.)

**Comment by damofthemoon** [comment]
I like the idea, I look forward to test it :)

**Comment by sarahec** [comment]
Closing due to not having the time to pursue
